version: "3"
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit_webhooks"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "webhooks-rabbit"
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
